# 大模型API配置
openai:
  api_key: "zhangxuhao2005@shu.edu.cn"
  base_url: "https://api.deepseek.com/v1"

# 路径配置
paths:
  input_video: data/input/input_video.mp4
  output_video: data/output/output_video.mp4
  process_video: data/output/process_video.mp4
  frames_dir: data/cache/frames
  frames_processed_dir: data/cache/frames_processed
  frames_cropped_dir: data/cache/frames_cropped
  frames_blurred_dir: data/cache/frames_blurred
  output_srt: data/output/output_subtitles.srt
